#!/bin/sh


echo "PATCH /customers - Update Jane Doe's (ID3) details, but not name"
curl -XPATCH -i --data "{  \
  \"phone\":\"555-456\", \
  \"contacted\":true, \
  \"role\":\"New Lead\", \
  \"email\":\"testuser@udacity.com\" }" \
  --header 'Content-Type: application/json' \
  localhost:3000/customers/3

echo ""
echo "PATCH /customers - Broken JSON - should return bad request (400)"
curl -XPATCH -i --data "{ \"name\":\"Test User\"\
  \"phone\":\"555-456\", \
  \"contacted\":true, \
  \"role\":\"New Lead\", \
  \"email\":\"testuser@udacity.com\" }" \
  --header 'Content-Type: application/json' \
  localhost:3000/customers/2

echo ""
echo "PATCH /customers - Override John Doe (ID2) to Test User"
curl -XPATCH -i --data "{ \"name\":\"Test User\",\
  \"phone\":\"555-456\", \
  \"contacted\":true, \
  \"role\":\"New Lead\", \
  \"email\":\"testuser@udacity.com\" }" \
  --header 'Content-Type: application/json' \
  localhost:3000/customers/2

