#!/bin/sh


echo "get /customers"
curl -i localhost:3000/customers

echo ""
echo "get customer no 1"
curl -i localhost:3000/customers/1

echo ""
echo "get customer no 2"
curl -i localhost:3000/customers/2

echo ""
echo "get customer no 3"
curl -i localhost:3000/customers/3

echo ""
echo "get non existing customers 4"
curl -i localhost:3000/customers/4
